UNAME := $(shell uname -s)

.PHONY: default
default: help

.PHONY: help
help: ### This help screen.
ifeq ($(UNAME), Linux); then
	@grep -P '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'
else
	@awk -F ':.*###' '$$0 ~ FS {printf "%15s%s\n", $$1 ":", $$2}' $(MAKEFILE_LIST) | grep -v '@awk' | sort
endif

.PHONY: generate
generate: generate-ci-config

.PHONY: generate-ci-config
generate-ci-config: ### Generate the CI YAML from jsonnet input
	( \
		printf -- '---\n\n# Generated by "make generate-ci-config"\n# Do not edit!!\n\n'; \
		jsonnet --string .gitlab-ci.jsonnet | yq e -P - \
	) > .gitlab-ci.yml
