---
# Source: gitlab/charts/registry/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: gitlab-registry
  namespace: gitlab
  labels:
    app: registry
    chart: registry-0.2.0
    release: gitlab
    heritage: Tiller

  annotations:

spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: registry
    - port: 5001
      targetPort: 5001
      protocol: TCP
      name: registry-prometheus
  selector:
    app: registry
    release: gitlab
