---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor/charts
    contents:
      - path: gitlab/pre
        git:
          url: git@dev.gitlab.org:gitlab/charts/gitlab.git
          ref: e54285b8f778891f3d122c36b1d10aca1ffc556c
        excludePaths:
          - '.git/**'
          - '.gitignore'
          - 'doc/**'
          - 'examples/**'
          - 'scripts/**'
          - 'spec/**'
      - path: gitlab/gstg
        git:
          url: git@dev.gitlab.org:gitlab/charts/gitlab.git
          ref: 77436bcdb0d5494d707ff73f8d889fca5ca2df9c
        excludePaths:
          - '.git/**'
          - '.gitignore'
          - 'doc/**'
          - 'examples/**'
          - 'scripts/**'
          - 'spec/**'
      - path: gitlab/gprd
        git:
          url: git@dev.gitlab.org:gitlab/charts/gitlab.git
          ref: 77436bcdb0d5494d707ff73f8d889fca5ca2df9c
        excludePaths:
          - '.git/**'
          - '.gitignore'
          - 'doc/**'
          - 'examples/**'
          - 'scripts/**'
          - 'spec/**'
      - path: gitlab-runner/pre
        git:
          url: git@dev.gitlab.org:gitlab/charts/gitlab-runner.git
          ref: 20683318add4eb99a8a8508932860c20f0ae70f6
        excludePaths:
          - '.git/**'
          - '.gitignore'
          - 'doc/**'
          - 'examples/**'
          - 'scripts/**'
          - 'spec/**'
