---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor/charts
    contents:
      - path: gitlab/pre
        git:
          url: git@dev.gitlab.org:gitlab/charts/gitlab.git
          ref: d6745f35b096c25b8b52fe4d8271c76036273cb7
        excludePaths:
          - '.git/**'
          - 'doc/**'
          - 'examples/**'
          - 'scripts/**'
          - 'spec/**'
      - path: gitlab/gstg
        git:
          url: git@dev.gitlab.org:gitlab/charts/gitlab.git
          ref: 1ea8fdae83d5c7f8e095641539bacb4a51bc8ead
        excludePaths:
          - '.git/**'
          - 'doc/**'
          - 'examples/**'
          - 'scripts/**'
          - 'spec/**'
      - path: gitlab/gprd
        git:
          url: git@dev.gitlab.org:gitlab/charts/gitlab.git
          ref: 1ea8fdae83d5c7f8e095641539bacb4a51bc8ead
        excludePaths:
          - '.git/**'
          - 'doc/**'
          - 'examples/**'
          - 'scripts/**'
          - 'spec/**'
      - path: gitlab-runner/pre
        git:
          url: git@dev.gitlab.org:gitlab/charts/gitlab-runner.git
          ref: 20683318add4eb99a8a8508932860c20f0ae70f6
        excludePaths:
          - '.git/**'
          - 'doc/**'
          - 'examples/**'
          - 'scripts/**'
          - 'spec/**'
