---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor/charts
    contents:
      - path: gitlab/pre
        git:
          url: git@dev.gitlab.org:gitlab/charts/gitlab.git
          ref: 6d5de06e9b86d6f687eb9bebfeb69b750697f4a5
        excludePaths:
          - '.git/**'
          - '.gitignore'
          - 'doc/**'
          - 'examples/**'
          - 'scripts/**'
          - 'spec/**'
      - path: gitlab/gstg
        git:
          url: git@dev.gitlab.org:gitlab/charts/gitlab.git
          ref: 6d5de06e9b86d6f687eb9bebfeb69b750697f4a5
        excludePaths:
          - '.git/**'
          - '.gitignore'
          - 'doc/**'
          - 'examples/**'
          - 'scripts/**'
          - 'spec/**'
      - path: gitlab/gprd
        git:
          url: git@dev.gitlab.org:gitlab/charts/gitlab.git
          ref: 5ca661235c4148cb54822ef8fa4b0e480ab2a440
        excludePaths:
          - '.git/**'
          - '.gitignore'
          - 'doc/**'
          - 'examples/**'
          - 'scripts/**'
          - 'spec/**'
      - path: gitlab-runner/pre
        git:
          url: git@dev.gitlab.org:gitlab/charts/gitlab-runner.git
          ref: 20683318add4eb99a8a8508932860c20f0ae70f6
        excludePaths:
          - '.git/**'
          - '.gitignore'
          - 'doc/**'
          - 'examples/**'
          - 'scripts/**'
          - 'spec/**'
