---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor/charts
    contents:
      - path: gitlab/pre
        git:
          url: git@dev.gitlab.org:gitlab/charts/gitlab.git
          ref: 8f8d255d74a83881702e60f3d3cbefb489d077bd
        excludePaths:
          - '.git/**'
          - '.gitignore'
          - 'doc/**'
          - 'examples/**'
          - 'scripts/**'
          - 'spec/**'
      - path: gitlab/gstg
        git:
          url: git@dev.gitlab.org:gitlab/charts/gitlab.git
          ref: 185c26aff38295742e4d9264fa920c1775883baa
        excludePaths:
          - '.git/**'
          - '.gitignore'
          - 'doc/**'
          - 'examples/**'
          - 'scripts/**'
          - 'spec/**'
      - path: gitlab/gprd
        git:
          url: git@dev.gitlab.org:gitlab/charts/gitlab.git
          ref: 8f8d255d74a83881702e60f3d3cbefb489d077bd
        excludePaths:
          - '.git/**'
          - '.gitignore'
          - 'doc/**'
          - 'examples/**'
          - 'scripts/**'
          - 'spec/**'
      - path: bitnami/common
        helmChart:
          name: common
          version: 2.x
          repository:
            url: https://charts.bitnami.com/bitnami
