---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor/charts
    contents:
      - path: gitlab/pre
        git:
          url: git@dev.gitlab.org:gitlab/charts/gitlab.git
          ref: 30b26521017178031bf2cfdacd3d4eab78e8af82
        excludePaths:
          - '.git/**'
          - '.gitignore'
          - 'doc/**'
          - 'examples/**'
          - 'scripts/**'
          - 'spec/**'
      - path: gitlab/gstg
        git:
          url: git@dev.gitlab.org:gitlab/charts/gitlab.git
          ref: 30b26521017178031bf2cfdacd3d4eab78e8af82
        excludePaths:
          - '.git/**'
          - '.gitignore'
          - 'doc/**'
          - 'examples/**'
          - 'scripts/**'
          - 'spec/**'
      - path: gitlab/gprd
        git:
          url: git@dev.gitlab.org:gitlab/charts/gitlab.git
          ref: 30b26521017178031bf2cfdacd3d4eab78e8af82
        excludePaths:
          - '.git/**'
          - '.gitignore'
          - 'doc/**'
          - 'examples/**'
          - 'scripts/**'
          - 'spec/**'
