---
bases:
  - "../../bases/helmDefaults.yaml"
  - "../../bases/environments.yaml"

---
{{ $namespace := .Values | getOrNil "gitlab_extras.namespace" | default "gitlab" }}
repositories:
- name: "kubernetes-incubator"
  url: "https://charts.helm.sh/incubator"

releases:
- name:  {{ .Values | getOrNil "gitlab_extras.release_name" | default "gitlab-extras" }}
  chart: "kubernetes-incubator/raw"
  namespace: {{ $namespace }}
  version: "0.2.3"
  values:
    - values.yaml.gotmpl
