---
bases:
  - "../../bases/helmDefaults.yaml"
  - "../../bases/environments.yaml"

---
repositories:
- name: "gitlab-runner"
  url: "https://charts.gitlab.io"

releases:
- name:  gitlab-runner
  chart: "gitlab-runner/gitlab-runner"
  namespace: {{ .Values | getOrNil "gitlab_runner.namespace" | default "gitlab-runner" }}
  version: "0.27.0"
  installed: {{ .Values | getOrNil "gitlab_runner.enabled" | default "false" }}
  values:
    - values.yaml.gotmpl
