apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plantuml.fullname" . }}
  labels:
    {{ include "plantuml.labels" . | indent 4 | trim }}
data:
  nginx.conf: |
    server {
      listen {{ .Values.service.port }} default_server;
      listen [::]:{{ .Values.service.port }} default_server;

      server_name {{ .Values.nginx_sidecar.server_name }};

      location / {
          return 301 {{ .Values.nginx_sidecar.redirect_url }};
      }

      location /png {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        if ($http_x_forwarded_proto = 'http') {
             return 301 https://$server_name$request_uri;
        }
        limit_except GET {
            deny all;
        }
        proxy_pass http://localhost:8080/png;
        proxy_hide_header access-control-allow-origin;
        add_header X-Frame-Options SAMEORIGIN always;
      }
    }
