{{- if .Values.nginx_sidecar.enabled -}}
{{- $values := .Values -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plantuml.fullname" . }}
  labels:
    {{ include "plantuml.labels" . | indent 4 | trim }}
{{- with .Values.nginx_sidecar }}
data:
  nginx.conf: |
    {{- if .rate_limit.enabled }}
    limit_req_zone $http_x_forwarded_for zone=rlimit:{{ .rate_limit.zone_size }} rate={{ .rate_limit.rate }};
    {{- end }}
    log_format json_combined escape=json
    '{'
      '"remote_addr": "$remote_addr",'
      '"remote_user": "$remote_user",'
      '"timestamp": "$time_iso8601",'
      '"request": "$request",'
      '"status": "$status",'
      '"request_time": "$request_time",'
      '"body_bytes_sent": "$body_bytes_sent",'
      '"http_referer": "$http_referer",'
      '"http_user_agent": "$http_user_agent",'
      '"http_x_forwarded_for": "$http_x_forwarded_for",'
      '"upstream_response_time": "$upstream_response_time",'
      '"connection":"$connection",'
      '"connection_requests": "$connection_requests",'
      '"connections_active": "$connections_active",'
      '"connections_reading": "$connections_reading",'
      '"connections_writing": "$connections_writing",'
      '"connections_waiting": "$connections_waiting"'
    '}';
    server {
      listen {{ .port | default $values.service.port }} default_server;
      listen [::]:{{ .port | default $values.service.port }} default_server;

      server_name {{ .server_name }};
      access_log /var/log/nginx/access.log json_combined;
      server_tokens off;
      {{- if .redirect.enabled }}
      location / {
          return 301 {{ .redirect.url }};
      }
      {{- end }}
      location ~ ^/({{ join "|" .enabled_urls }}) {
        {{- if .rate_limit.enabled }}
        limit_req zone=rlimit burst={{ .rate_limit.burst }} nodelay;
        limit_req_status {{ .rate_limit.status_code }};
        {{- end }}
        {{- range .set_headers }}
        proxy_set_header {{ . }};
        {{- end }}
        if ($http_x_forwarded_proto = 'http') {
             return 301 https://$server_name$request_uri;
        }
        {{- if .limit_except.enabled }}
        limit_except {{ join " " .limit_except.req_methods }} {
            deny all;
        }
        {{- end }}
        proxy_pass http://localhost:{{ .proxy_port | default $values.port }};
        {{- range .hide_headers }}
        proxy_hide_header {{ . }};
        {{- end }}
        {{- range .add_headers }}
        add_header {{ . }};
        {{- end }}
      }
    }
{{- end }}
{{- end }}
