---
environments:
  # This is a dummy environment used for base values that can
  # be merged into other environments.
  __base:
    values:
      # These defaults are for services that are enabled
      # on all regional clusters, in all environments
      # These are read by values.yaml.gotmpl
      - &regional_cluster_defaults
        registry:
          enabled: true
        gitlab:
          webservice:
            enabled: false
          sidekiq:
            enabled: true
          gitlab-shell:
            enabled: false
          mailroom:
            enabled: true
          kas:
            enabled: false
      # These services are only installed in the
      # regional cluster, so we disable them for
      # all zonal clusters, regardless of the environment.
      - &zonal_cluster_defaults
        registry:
          enabled: true
        gitlab:
          sidekiq:
            enabled: false
          mailroom:
            enabled: false
          gitlab-shell:
            enabled: true
          webservice:
            enabled: true
          kas:
            enabled: false
        gitlab_extras:
          installed: false

  ops:
    values:
      - <<: *regional_cluster_defaults
      -
        google_project: "gitlab-ops"
        gitlab_endpoint: "https://ops.gitlab.net"
  pre:
    values:
      - <<: *regional_cluster_defaults
      - &pre_values
        env_prefix: pre
        google_project: "gitlab-pre"
        gitlab_endpoint: "https://pre.gitlab.com"
        registry_deployment_for_image_tag: "gitlab-registry"
        gitlab:
          gitlab-shell:
            enabled: true
          webservice:
            enabled: true
          kas:
            enabled: true
        cluster: pre-gitlab-gke
        region: us-east1
        gitlab_extras:
          installed: true
        kas:
          managed_cert_name: kas-pre-gitlab-com
          domain: kas.pre.gitlab.com

  gstg:
    values:
      - <<: *regional_cluster_defaults
      - &gstg_values
        env_prefix: gstg
        google_project: "gitlab-staging-1"
        gitlab_endpoint: "https://staging.gitlab.com"
        registry_deployment_for_image_tag: "gitlab-registry"
        cluster: gstg-gitlab-gke
        region: us-east1
        gitlab_extras:
          installed: true
        gitlab:
          kas:
            enabled: true
        kas:
          managed_cert_name: kas-staging-gitlab-com
          domain: kas.staging.gitlab.com
      # This can be removed once
      # https://gitlab.com/gitlab-com/gl-infra/delivery/-/issues/1321
      # is complete
      - registry:
          nodeSelector:
            type: default


  # Zonal clusters for gstg, these three environments
  # inherit from the gstg environemnt, which is the
  # regional cluster
  gstg-us-east1-b:
    values:
      - <<: *regional_cluster_defaults
      - <<: *gstg_values
      - <<: *zonal_cluster_defaults
      -
        cluster: gstg-us-east1-b
        region: us-east1-b
      # This can be removed once
      # https://gitlab.com/gitlab-com/gl-infra/delivery/-/issues/1321
      # is complete
      - registry:
          nodeSelector:
            type: registry

  gstg-us-east1-c:
    values:
      - <<: *regional_cluster_defaults
      - <<: *gstg_values
      - <<: *zonal_cluster_defaults
      -
        cluster: gstg-us-east1-c
        region: us-east1-c
      # This can be removed once
      # https://gitlab.com/gitlab-com/gl-infra/delivery/-/issues/1321
      # is complete
      - registry:
          nodeSelector:
            type: registry

  gstg-us-east1-d:
    values:
      - <<: *regional_cluster_defaults
      - <<: *gstg_values
      - <<: *zonal_cluster_defaults
      -
        cluster: gstg-us-east1-d
        region: us-east1-d
      # This can be removed once
      # https://gitlab.com/gitlab-com/gl-infra/delivery/-/issues/1321
      # is complete
      - registry:
          nodeSelector:
            type: registry

  gprd-cny:
    values:
      - <<: *regional_cluster_defaults
      -
        google_project: "gitlab-production"
        gitlab_endpoint: "https://gitlab.com"
        gitlab_secrets_gkms_source: "gprd"
        gitlab_release_name: "gitlab-cny"
        gitlab_secrets_release_name: "gitlab-secrets-cny"
        gitlab_secrets_namespace: "gitlab-cny"
        gitlab_namespace: "gitlab-cny"
      # Canary uses the same bucket as production
        registry_bucket_name: "gitlab-gprd-registry"
        registry_deployment_for_image_tag: "gitlab-cny-registry"
        gitlab_chef_source_name: "gprd"
        stage: "cny"
        gitlab:
          gitlab-shell:
            enabled: true
          webservice:
            enabled: true

  gprd:
    values:
      - <<: *regional_cluster_defaults
      - &gprd_values
        env_prefix: gprd
        google_project: "gitlab-production"
        gitlab_endpoint: "https://gitlab.com"
        registry_deployment_for_image_tag: "gitlab-registry"
        cluster: gprd-gitlab-gke
        region: us-east1

  # Zonal clusters for gprd, these three environments
  # inherit from the gprd environemnt, which is the
  # regional cluster
  gprd-us-east1-b:
    values:
      - <<: *regional_cluster_defaults
      - <<: *gprd_values
      - <<: *zonal_cluster_defaults
      -
        cluster: gprd-us-east1-b
        region: us-east1-b

  gprd-us-east1-c:
    values:
      - <<: *regional_cluster_defaults
      - <<: *gprd_values
      - <<: *zonal_cluster_defaults
      -
        cluster: gprd-us-east1-c
        region: us-east1-c

  gprd-us-east1-d:
    values:
      - <<: *regional_cluster_defaults
      - <<: *gprd_values
      - <<: *zonal_cluster_defaults
      -
        cluster: gprd-us-east1-d
        region: us-east1-d
