---
environments:
  # This is a dummy environment used for base values that can
  # be merged into other environments.
  __base:
    values:
      # These defaults are for services that are enabled
      # on all regional clusters, in all environments
      # These are read by values.yaml.gotmpl
      - &regional_cluster_defaults
        # Registry is disabled by default on the regional cluster
        # and enabled selectively for preprod and canary
        registry:
          enabled: false
        gitlab:
          webservice:
            enabled: false
          sidekiq:
            enabled: true
          gitlab-shell:
            enabled: false
          mailroom:
            enabled: true
          kas:
            enabled: true
        nginx-ingress:
          enabled: false
      # These services are only installed in the
      # regional cluster, so we disable them for
      # all zonal clusters, regardless of the environment.
      - &zonal_cluster_defaults
        registry:
          enabled: true
        gitlab:
          sidekiq:
            enabled: false
          mailroom:
            enabled: false
          gitlab-shell:
            enabled: true
          webservice:
            enabled: true
          kas:
            enabled: false
        gitlab_extras:
          api_no_proxy: true
          ingress_readiness: true
        nginx-ingress:
          enabled: true

  ops:
    values:
      - <<: *regional_cluster_defaults
      -
        google_project: "gitlab-ops"
        gitlab_endpoint: "https://ops.gitlab.net"
  pre:
    values:
      - <<: *regional_cluster_defaults
      - &pre_values
        gitlab_runner_chart_version: 20683318add4eb99a8a8508932860c20f0ae70f6
        gitlab_chart_version: 425d44208c13b97faa09f65747e09ec28ec31f4c
        env_prefix: pre
        google_project: "gitlab-pre"
        gitlab_domain: "pre.gitlab.com"
        gitlab_endpoint: "https://pre.gitlab.com"
        registry:
          enabled: true
        registry_deployment_for_image_tag: "gitlab-registry"
        registry_api_host: "registry.pre.gitlab.com"
        registry_bucket_name: "gitlab-pre-container-registry"
        registry_version: v3.17.0-gitlab
        gitlab:
          gitlab-shell:
            enabled: true
          webservice:
            enabled: true
        cluster: pre-gitlab-gke
        region: us-east1
        kas:
          managed_cert_name: kas-pre-gitlab-com
          domain: kas.pre.gitlab.com
        gitlab_runner:
          enabled: true
          namespace: gitlab-runner
        gitlab_extras:
          api_no_proxy: true
          ingress_readiness: true
        nginx-ingress:
          enabled: true
        ssh:
          ed25519_pub: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKXsGj8bJCsKmemysUHSf5KFU8FK7d1V9tc17mDPwaoq"
          dsa_pub: "ssh-dss AAAAB3NzaC1kc3MAAACBAOaMyanI+FZ/JzTqRvDbHCTdXEeEtbqxMYCaJ2w6gfiql3PirxSPv3gvDsSxrvThrYfgtfy4ntU6Fe+U0PjxstWvdw8rTY7pzGkXDZWn6Rvw9MKxKeOGlAHNeJU52UynXtzcWZAr8q5V8FcjdZeMNwDnk04DCLxhab3eLTCwa2ZdAAAAFQD0P4b+KRdfFEV76ASKDZrK3xNBWwAAAIEAguFw2EldeJrgHAxHe1buwjZ24cLEB6R/EK9omg5OXIIyosxQIzb6wkcrqdJLpH7Ekj4vZBfz8TySM7ac7NUCjrQxlXjMiqnxz/rFarVHvfm40tVnActciMwbG3/JcHMGGz9Qqaa3wiSakF2LPF3BILFn1QdK1agxJxPHj14Vyl0AAACAdJrn8OK/hebmzy+B1wf5LjhnqYixNQJWuk42/A04VeYbE08GdRAikBPiFWrGLCZcdvx7ovBbKNHCqsXSy9PVz64zcvEL2zNp+VOJu1NIdWF0DimOj3qeL4zdPbh/i1cVfy1fhiqxkbqGro3jO44o6sDPT2H/1YBfk91VAZA0L0Q="
          ecdsa_pub: "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKz88Ffi/VaKGYIqgPvV1NKgJBcSTakl48zR5gM5ZA0KPkQA57likgtlDNw+XSoX+M/rOCRw2m0za7/LR+eKY4I="
          rsa_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCoSAn1VeQ4tpJ+lPYbKYo6A9TlHsTc3tzmKuPp7/83DUzgUBFYvGXBpcRYHHUCh+JSpcC9ubx+nxzETKCEA7O0nAAqF2aAx666pFaJvTlFQlHVKLoP20wc/KtP6OFG5Vw1SrzTMiB8S3Ot2nAgvRCO4L7kgHfRYjLjSIA+iXJutcP0nk8qV4Tj/TnEwaSMk0qcPkpcFVy3kUYirTmx0ukuWhfY5dr9DOKldCRjfPjoV+Wcr/WpjXVcrcBz3CVKnrhOpCROyxhNO5utcbtyZHK0HuQk7VIgd/r+pwBeAAkkZ679GP/C7gX6vHwqHiaWvGxETynjbpOK9ssKo3TbJzkl"

  gstg:
    values:
      - <<: *regional_cluster_defaults
      - &gstg_values
        gitlab_chart_version: 425d44208c13b97faa09f65747e09ec28ec31f4c
        env_prefix: gstg
        google_project: "gitlab-staging-1"
        gitlab_domain: "staging.gitlab.com"
        gitlab_endpoint: "https://staging.gitlab.com"
        gitlab_internal_lb_dns_address: "int.gstg.gitlab.net"
        registry_api_host: "registry.staging.gitlab.com"
        registry_deployment_for_image_tag: "gitlab-registry"
        registry_version: v3.17.0-gitlab
        cluster: gstg-gitlab-gke
        region: us-east1
        kas:
          managed_cert_name: kas-staging-gitlab-com
          domain: kas.staging.gitlab.com
        ssh:
          ed25519_pub: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf"
          dsa_pub: "ssh-dss AAAAB3NzaC1kc3MAAACBAMPKInNPflcRle9F5Qt2j9aI0EZuWQzdXTbYvsl+ChaacqCOWRMiOmXHXqetFz6jD/6Fcqg20ZATxqSskQBaRn97O/mbH+GQk4d3zw9WAEURicE8rKJop3qGtdfFxLzrTuF/PAkKRDMmutT3hwZIOO8CFWOl1BiuUYTncJTeonrfAAAAFQCujauoy3Yy+ul72b/WsTECUPj9yQAAAIBIV2yyF7RZf7IYS8tsWcKP7Y5Bv9eFdbvbtsaxcFCHcmHIGoJQrIdPoueoOb5EUTYz0NgYKsKaZzDZkgFk28GsmLxKvhnPjaw0lJVSKRchEE5xVlamOlabiRMjQ7X/bAdejkBJe96AjZZL3UO4acpwfy3Tnnap0w6YCDeaxoyHpwAAAIAU+dyNaL3Hy15VIV32QwWMekvxeptUY/DW03LNcgZZDoin87TE9xuQhM0qF3pi2i2a2ExuslgdttmYWvrbEz8eW+RFgvT5pKwWpalKWetHvtN3oYZP37ZIO1Y3Hd5A4YVcpYp1ccRayveLlCRwxb4HdGXT2OmYU+lmvimIR8zQ6A=="
          ecdsa_pub: "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1fVkhtj3Hw9xjLVXVYrU9QlYWrOLXBpQ6KWjbjTDTdDkoohFzgbEY="
          rsa_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsj2bNKTBSpIYDEGk9KxsGh3mySTRgMtXL583qmBpzeQ+jqCMRgBqB98u3z++J1sKlXHWfM9dyhSevkMwSbhoR8XIq/U0tCNyokEi/ueaBMCvbcTHhO7FcwzY92WK4Yt0aGROY5qX2UKSeOvuP4D6TPqKF1onrSzH9bx9XUf2lEdWT/ia1NEKjunUqu1xOB/StKDHMoX4/OKyIzuS0q/T1zOATthvasJFoPrAjkohTyaDUz2LN5JoH839hViyEG82yB+MjcFV5MU3N1l1QL3cVUCh93xSaua1N85qivl+siMkPGbO5xR/En4iEY6K2XPASUEMaieWVNTRCtJ4S8H+9"

  gstg-cny:
    values:
      - <<: *regional_cluster_defaults
      - <<: *gstg_values
      -
        gitlab:
          gitlab-shell:
            enabled: true
          webservice:
            enabled: true
          kas:
            enabled: false
        gitlab_chef_source_name: "gstg"
        gitlab_extras:
          api_no_proxy: true
          ingress_readiness: true
          namespace: "gitlab-cny"
        gitlab_namespace: "gitlab-cny"
        gitlab_release_name: "gitlab-cny"
        gitlab_secrets_gkms_source: "gstg"
        gitlab_secrets_namespace: "gitlab-cny"
        gitlab_secrets_release_name: "gitlab-secrets-cny"
        nginx-ingress:
          enabled: true
        registry_bucket_name: "gitlab-gstg-registry"
        registry_deployment_for_image_tag: "gitlab-cny-registry"
        registry_api_host: "registry.staging.gitlab.com"
        registry:
          enabled: true
        stage: "cny"
        web:
          enabled: true

  # Zonal clusters for gstg, these three environments
  # inherit from the gstg environemnt, which is the
  # regional cluster
  gstg-us-east1-b:
    values:
      - <<: *regional_cluster_defaults
      - <<: *gstg_values
      - <<: *zonal_cluster_defaults
      -
        cluster: gstg-us-east1-b
        region: us-east1-b

  gstg-us-east1-c:
    values:
      - <<: *regional_cluster_defaults
      - <<: *gstg_values
      - <<: *zonal_cluster_defaults
      -
        cluster: gstg-us-east1-c
        region: us-east1-c

  gstg-us-east1-d:
    values:
      - <<: *regional_cluster_defaults
      - <<: *gstg_values
      - <<: *zonal_cluster_defaults
      -
        cluster: gstg-us-east1-d
        region: us-east1-d

  gprd:
    values:
      - <<: *regional_cluster_defaults
      - &gprd_values
        cluster: gprd-gitlab-gke
        env_prefix: gprd
        gitlab_chart_version: 7d847fbc8ec7c12d87dc89e22d8a35fefc59398c
        gitlab_domain: "gitlab.com"
        gitlab_endpoint: "https://gitlab.com"
        gitlab_internal_lb_dns_address: "int.gprd.gitlab.net"
        google_project: "gitlab-production"
        kas:
          managed_cert_name: kas-gitlab-com
          domain: kas.gitlab.com
        region: us-east1
        registry_api_host: "registry.gitlab.com"
        registry_deployment_for_image_tag: "gitlab-registry"
        registry_version: v3.17.0-gitlab
        ssh:
          dsa_pub: "ssh-dss AAAAB3NzaC1kc3MAAACBAMPKInNPflcRle9F5Qt2j9aI0EZuWQzdXTbYvsl+ChaacqCOWRMiOmXHXqetFz6jD/6Fcqg20ZATxqSskQBaRn97O/mbH+GQk4d3zw9WAEURicE8rKJop3qGtdfFxLzrTuF/PAkKRDMmutT3hwZIOO8CFWOl1BiuUYTncJTeonrfAAAAFQCujauoy3Yy+ul72b/WsTECUPj9yQAAAIBIV2yyF7RZf7IYS8tsWcKP7Y5Bv9eFdbvbtsaxcFCHcmHIGoJQrIdPoueoOb5EUTYz0NgYKsKaZzDZkgFk28GsmLxKvhnPjaw0lJVSKRchEE5xVlamOlabiRMjQ7X/bAdejkBJe96AjZZL3UO4acpwfy3Tnnap0w6YCDeaxoyHpwAAAIAU+dyNaL3Hy15VIV32QwWMekvxeptUY/DW03LNcgZZDoin87TE9xuQhM0qF3pi2i2a2ExuslgdttmYWvrbEz8eW+RFgvT5pKwWpalKWetHvtN3oYZP37ZIO1Y3Hd5A4YVcpYp1ccRayveLlCRwxb4HdGXT2OmYU+lmvimIR8zQ6A=="
          ecdsa_pub: "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1fVkhtj3Hw9xjLVXVYrU9QlYWrOLXBpQ6KWjbjTDTdDkoohFzgbEY="
          ed25519_pub: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf"
          rsa_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsj2bNKTBSpIYDEGk9KxsGh3mySTRgMtXL583qmBpzeQ+jqCMRgBqB98u3z++J1sKlXHWfM9dyhSevkMwSbhoR8XIq/U0tCNyokEi/ueaBMCvbcTHhO7FcwzY92WK4Yt0aGROY5qX2UKSeOvuP4D6TPqKF1onrSzH9bx9XUf2lEdWT/ia1NEKjunUqu1xOB/StKDHMoX4/OKyIzuS0q/T1zOATthvasJFoPrAjkohTyaDUz2LN5JoH839hViyEG82yB+MjcFV5MU3N1l1QL3cVUCh93xSaua1N85qivl+siMkPGbO5xR/En4iEY6K2XPASUEMaieWVNTRCtJ4S8H+9"

  gprd-cny:
    values:
      - <<: *regional_cluster_defaults
      - <<: *gprd_values
      -
        gitlab:
          gitlab-shell:
            enabled: true
          webservice:
            enabled: true
          kas:
            enabled: false
        gitlab_chef_source_name: "gprd"
        gitlab_extras:
          api_no_proxy: true
          ingress_readiness: true
          namespace: "gitlab-cny"
        gitlab_namespace: "gitlab-cny"
        gitlab_release_name: "gitlab-cny"
        gitlab_secrets_gkms_source: "gprd"
        gitlab_secrets_namespace: "gitlab-cny"
        gitlab_secrets_release_name: "gitlab-secrets-cny"
        nginx-ingress:
          enabled: true
        registry:
          enabled: true
        registry_api_host: "registry.gitlab.com"
        registry_bucket_name: "gitlab-gprd-registry"
        registry_deployment_for_image_tag: "gitlab-cny-registry"
        stage: "cny"
        web:
          enabled: true

  # Zonal clusters for gprd, these three environments
  # inherit from the gprd environemnt, which is the
  # regional cluster
  gprd-us-east1-b:
    values:
      - <<: *regional_cluster_defaults
      - <<: *gprd_values
      - <<: *zonal_cluster_defaults
      -
        cluster: gprd-us-east1-b
        region: us-east1-b

  gprd-us-east1-c:
    values:
      - <<: *regional_cluster_defaults
      - <<: *gprd_values
      - <<: *zonal_cluster_defaults
      -
        cluster: gprd-us-east1-c
        region: us-east1-c

  gprd-us-east1-d:
    values:
      - <<: *regional_cluster_defaults
      - <<: *gprd_values
      - <<: *zonal_cluster_defaults
      -
        cluster: gprd-us-east1-d
        region: us-east1-d
