---
environments:
  # This is a dummy environment used for base values that can
  # be merged into other environments.
  __base:
    values:
      # These defaults are for services that are enabled
      # on all regional clusters, in all environments
      # These are read by values.yaml.gotmpl
      - &regional_cluster_defaults
        registry:
          enabled: true
        gitlab:
          webservice:
            enabled: true
          sidekiq:
            enabled: true
          gitlab-shell:
            enabled: false
          mailroom:
            enabled: true
      # These services are only installed in the
      # regional cluster, so we disable them for
      # all zonal clusters, regardless of the environment.
      - &zonal_cluster_defaults
        registry:
          enabled: false
        gitlab:
          sidekiq:
            enabled: false
          mailroom:
            enabled: false

  ops:
    values:
      - <<: *regional_cluster_defaults
      -
        google_project: "gitlab-ops"
        gitlab_endpoint: "https://ops.gitlab.net"
  pre:
    values:
      - <<: *regional_cluster_defaults
      - &pre_values
        env_prefix: pre
        google_project: "gitlab-pre"
        gitlab_endpoint: "https://pre.gitlab.com"
        registry_deployment_for_image_tag: "gitlab-registry"
        gitlab:
          gitlab-shell:
            enabled: true
        cluster: pre-gitlab-gke
        region: us-east1

  # Zonal clusters for pre, these three environments
  # inherit from the pre environemnt, which is the
  # regional cluster
  pre-us-east1-b:
    values:
      - <<: *regional_cluster_defaults
      - <<: *pre_values
      - <<: *zonal_cluster_defaults
      -
        cluster: pre-us-east1-b
        region: us-east1-b

  pre-us-east1-c:
    values:
      - <<: *regional_cluster_defaults
      - <<: *pre_values
      - <<: *zonal_cluster_defaults
      -
        cluster: pre-us-east1-c
        region: us-east1-c

  pre-us-east1-d:
    values:
      - <<: *regional_cluster_defaults
      - <<: *pre_values
      - <<: *zonal_cluster_defaults
      -
        cluster: pre-us-east1-d
        region: us-east1-d

  gstg:
    values:
      - <<: *regional_cluster_defaults
      - &gstg_values
        env_prefix: gstg
        google_project: "gitlab-staging-1"
        gitlab_endpoint: "https://staging.gitlab.com"
        registry_deployment_for_image_tag: "gitlab-registry"
        cluster: gstg-gitlab-gke
        region: us-east1
        ## TODO: After we migrate all environments to zonal clusters, this should move into the regional_cluster_defaults
        gitlab:
          webservice:
            enabled: false

  # Zonal clusters for gstg, these three environments
  # inherit from the gstg environemnt, which is the
  # regional cluster
  gstg-us-east1-b:
    values:
      - <<: *regional_cluster_defaults
      - <<: *gstg_values
      - <<: *zonal_cluster_defaults
      -
        cluster: gstg-us-east1-b
        region: us-east1-b
        ## TODO: After we migrate all environments to zonal clusters, this can be removed
        gitlab:
          webservice:
            enabled: true

  gstg-us-east1-c:
    values:
      - <<: *regional_cluster_defaults
      - <<: *gstg_values
      - <<: *zonal_cluster_defaults
      -
        cluster: gstg-us-east1-c
        region: us-east1-c
        ## TODO: After we migrate all environments to zonal clusters, this can be removed
        gitlab:
          webservice:
            enabled: true

  gstg-us-east1-d:
    values:
      - <<: *regional_cluster_defaults
      - <<: *gstg_values
      - <<: *zonal_cluster_defaults
      -
        cluster: gstg-us-east1-d
        region: us-east1-d
        ## TODO: After we migrate all environments to zonal clusters, this can be removed
        gitlab:
          webservice:
            enabled: true

  gprd-cny:
    values:
      - <<: *regional_cluster_defaults
      -
        google_project: "gitlab-production"
        gitlab_endpoint: "https://gitlab.com"
        gitlab_secrets_gkms_source: "gprd"
        gitlab_release_name: "gitlab-cny"
        gitlab_secrets_release_name: "gitlab-secrets-cny"
        gitlab_secrets_namespace: "gitlab-cny"
        gitlab_namespace: "gitlab-cny"
      # Canary uses the same bucket as production
        registry_bucket_name: "gitlab-gprd-registry"
        registry_deployment_for_image_tag: "gitlab-cny-registry"
        gitlab_chef_source_name: "gprd"
        stage: "cny"
  gprd:
    values:
      - <<: *regional_cluster_defaults
      -
        google_project: "gitlab-production"
        gitlab_endpoint: "https://gitlab.com"
        registry_deployment_for_image_tag: "gitlab-registry"
