---
environments:
  ops:
    values:
      - google_project: "gitlab-ops"
      - gitlab_endpoint: "https://ops.gitlab.net"
  pre:
    values:
      - google_project: "gitlab-pre"
      - gitlab_endpoint: "https://pre.gitlab.com"
  gstg:
    values:
      - google_project: "gitlab-staging-1"
      - gitlab_endpoint: "https://staging.gitlab.com"
  cny:
    values:
      - google_project: "gitlab-production"
      - gitlab_endpoint: "https://gitlab.com"
      - gitlab_secrets_gkms_source: "gprd"
      - gitlab_secrets_release_name: "gitlab-secrets-cny"
      - gitlab_secrets_namespace: "gitlab-cny"
  gprd:
    values:
      - google_project: "gitlab-production"
      - gitlab_endpoint: "https://gitlab.com"
