{{- range .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    {{- if $.Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" $.Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
    {{- if .labels }}
      {{- include "common.tplvalues.render" (dict "value" .labels "context" $) | nindent 4 }}
    {{- end }}
  {{- if or .annotations $.Values.commonAnnotations }}
  annotations:
    {{- if $.Values.commonAnnotations }}
      {{- include "common.tplvalues.render" (dict "value" $.Values.commonAnnotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .annotations }}
      {{- include "common.tplvalues.render" (dict "value" .annotations "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  secretStoreRef:
    kind: SecretStore
    name: {{ .secretStoreName | default (include "vault-secrets.secretStoreName" $) }}
  {{- /* https://github.com/helm/helm/issues/3164 */}}
  refreshInterval: {{ .refreshInterval | quote | default "0" }}
  {{- if .target }}
  target:
    {{- include "common.tplvalues.render" (dict "value" .target "context" $) | nindent 4 }}
  {{- end }}
  {{- if .data }}
  data:
    {{- include "common.tplvalues.render" (dict "value" .data "context" $) | nindent 4 }}
  {{- end }}
{{- end }}
