{{- range .Values.secretStores }}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .name | default (include "vault-secrets.secretStoreName" $) }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    {{- if $.Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" $.Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
    {{- if .labels }}
      {{- include "common.tplvalues.render" (dict "value" .labels "context" $) | nindent 4 }}
    {{- end }}
  {{- if or .annotations $.Values.commonAnnotations }}
  annotations:
    {{- if $.Values.commonAnnotations }}
      {{- include "common.tplvalues.render" (dict "value" $.Values.commonAnnotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .annotations }}
      {{- include "common.tplvalues.render" (dict "value" .annotations "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: {{ .authMountPath | default (include "vault-secrets.secretStoreMountPath" $) }}
          role: {{ .role }}
          serviceAccountRef:
            name: {{ template "vault-secrets.serviceAccountName" $ }}
      path: {{ .path | default (include "vault-secrets.secretStorePath" $) }}
      server: {{ .server | default (include "vault-secrets.secretStoreServer" $) }}
      version: {{ .version | default (include "vault-secrets.secretStoreVersion" $) }}
{{- end }}
