---
bases:
  - "../../bases/helmDefaults.yaml"
  - "../../bases/environments.yaml"

---
repositories:
  - name: gitlab
    url: git+ssh://git@dev.gitlab.org/gitlab/charts/gitlab.git@?ref={{env "CHART_VERSION" | default (.Environment.Values | getOrNil "gitlab_chart_version") }}

releases:
  - name: {{.Environment.Values | getOrNil "gitlab_release_name" | default "gitlab"}}
    namespace: {{.Environment.Values | getOrNil "gitlab_namespace" | default "gitlab"}}
    chart: gitlab/gitlab
    set:
      - name: "global.deployment.annotations.app\\.gitlab\\.com/app"
        value: {{env "CI_PROJECT_PATH_SLUG" | default "gitlab-com-gl-infra-k8s-workloads-gitlab-com"}}
      - name: "global.deployment.annotations.app\\.gitlab\\.com/env"
        value: {{env "CI_ENVIRONMENT_SLUG" | default .Environment.Name}}
      - name: "global.registry.bucket"
        value: "gitlab-{{ .Environment.Name }}-registry"

      - name: "registry.annotations.app\\.gitlab\\.com/app"
        value: {{env "CI_PROJECT_PATH_SLUG" | default "gitlab-com-gl-infra-k8s-workloads-gitlab-com"}}
      - name: "registry.annotations.app\\.gitlab\\.com/env"
        value: {{env "CI_ENVIRONMENT_SLUG" | default .Environment.Name}}
    values:
      - stage: {{.Environment.Values | getOrNil "stage" | default "main"}}
      - values/values.yaml.gotmpl
      - values/{{.Environment.Name}}.yaml.gotmpl
      - values/values-from-external-sources.yaml.gotmpl
