---
bases:
  - "../../bases/helmDefaults.yaml"
  - "../../bases/environments.yaml"

---
{{- $chart_source := env "CHART_SOURCE" | default (.Environment.Values | getOrNil "gitlab_chart" | default "gitlab/gitlab") }}
{{- $chart_version := env "CHART_VERSION" | default (.Environment.Values | getOrNil "gitlab_chart_version") | trim }}
repositories:
{{- if eq $chart_source "gitlab/gitlab" }}
- name: gitlab
  url: https://charts.gitlab.io/
{{- else if eq $chart_source "gitlab-s3/gitlab" }}
- name: gitlab-s3
  url: https://gitlab-charts.s3.amazonaws.com/
{{- else if eq $chart_source "gitlab-git/gitlab" }}
- name: gitlab-git
  url: http://127.0.0.1:8879/charts
{{- end }}

releases:
  - name: {{.Environment.Values | getOrNil "gitlab_release_name" | default "gitlab"}}
    namespace: {{.Environment.Values | getOrNil "gitlab_namespace" | default "gitlab"}}
    chart: {{ $chart_source }}
    version: {{ $chart_version }}
    set:
      - name: "global.deployment.annotations.app\\.gitlab\\.com/app"
        value: {{env "CI_PROJECT_PATH_SLUG" | default "gitlab-com-gl-infra-k8s-workloads-gitlab-com"}}
      - name: "global.deployment.annotations.app\\.gitlab\\.com/env"
        value: {{env "CI_ENVIRONMENT_SLUG" | default .Environment.Name}}
      - name: "global.registry.bucket"
        value: "gitlab-{{ .Environment.Name }}-registry"

      - name: "registry.annotations.app\\.gitlab\\.com/app"
        value: {{env "CI_PROJECT_PATH_SLUG" | default "gitlab-com-gl-infra-k8s-workloads-gitlab-com"}}
      - name: "registry.annotations.app\\.gitlab\\.com/env"
        value: {{env "CI_ENVIRONMENT_SLUG" | default .Environment.Name}}
    values:
      - values/values.yaml.gotmpl
      - values/{{.Environment.Name}}.yaml.gotmpl
      - values/values-from-external-sources.yaml.gotmpl
