{{- if .Values.ingress.enabled -}}
{{- $fullName := include "plantuml.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{ include "plantuml.labels" . | nindent 4 | trim }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  backend:
    serviceName: {{ $fullName }}
    servicePort: {{ .Values.service.port }}
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ .Values.service.port }}
{{- end }}
