{{- if .Values.networkpolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "plantuml.fullname" . }}
  labels:
    {{ include "plantuml.labels" . | nindent 4 | trim }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "plantuml.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    {{- if .Values.networkpolicy.egress.enabled }}
    - Egress
    {{- end }}
    {{- if .Values.networkpolicy.ingress.enabled }}
    - Ingress
    {{- end }}
  {{- if .Values.networkpolicy.ingress.enabled }}
  ingress:
    {{ toYaml .Values.networkpolicy.ingress.rules | nindent 4 }}
  {{- end -}}
  {{- if .Values.networkpolicy.egress.enabled }}
  egress:
    {{ toYaml .Values.networkpolicy.egress.rules | nindent 4 }}
  {{- end -}}
{{- end -}}
