apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "plantuml.fullname" . }}
  labels:
    {{ include "plantuml.labels" . | indent 4 | trim }}
spec:
  maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "plantuml.name" . }}
